chronorender:
    rendersettings:
        searchpaths: "./"
    camera:
        - filename: "default_camera.rib"
        # script:
            # file: "camera_script.py"
            # function: "render"
    lighting:
        - filename: "default_lighting.rib"
        # shader:
            # - name: "pointlight.sl"
    scene:
        - filename: "default_scene.rib"
    renderpass:
        - name: "defaultpass"
          settings: 
            resolution: 640 480
            display:
                output: "out.tif"
    simulation:
        data:
            datasource:
                - type: "csv"
                  resource: "./*.dat"
                  name: "defaultdata"
                  fields: [["id", integer],
                            ["pos_x", float], 
                            ["pos_y", float], 
                            ["pos_z", float], 
                            ["euler_x", float], 
                            ["euler_y", float], 
                            ["euler_z", float]]
        renderobject:
            - name: "particle"
              condition: "id >= 0"
              color: "0.8 0.1 0.1"
              geometry:
                  - type: "sphere"
                    radius: 0.888
